openapi: 3.0.3
paths:
  /hello:
    get:
      summary: Hello World
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World
info:
  title: Your API Title
  version: 1.0.0
  description: Your API Description