version: "3.8"

services:
  app:
    environment:
      SERVER_PORT: ${SERVER_PORT}
      MYSQL_PASSWORD: ${MY_SQL_ROOT_PASSWORD:-Admin@123}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/elearning
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_ROOT_PASSWORD:-Admin@123}
      MYSQL_DATABASE: elearning
      MYSQL_USER: myuser
      MYSQL_PASSWORD: user@123
    volumes:
      - elearning-db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  elearning-db: {}
